HomeWorkEleven/Controllers/TableController.cs
using HomeWorkEleven.Models;
using Microsoft.AspNetCore.Mvc;

namespace HomeWorkEleven.Controllers;

[Route("[controller]")]
public class TableController : Controller
{
    private static List<ProductModel?> ProductModels { get; set; } = new();
    private readonly Random _rnd = new();
    private static string[]? Name { get; set; }
    private static string[]? Title { get; set; }
    private static int Id { get; set; }

    [HttpGet]
    public string Get(string arg)
    {
        return arg;
    }

    public TableController()
    {
        Name = new[]
        {
            "автостопом по галактике", "Властелин Колец", "Велосипед - AKa2000", "Puma", "Война и Мир",
            "средство для мытья волос", "Lenovo Legion", "Xiaomi Mi 8", "Джинсы Louis Vuitton",
            "Язык программирования C++",
            "Искусство программирования", "Конкретная математика", "Крестный Отец", "Форсаж", "Божественная комедия",
            "HHH1242", "Монитор Асус ", "кроссовки Nike", "Фен Дайсон", "barbie",
            "rolex", "Ведьмак", "New York Times", "red dead redemption 2", "Сборник песен - Классика",
        };
        Title = new[]
        {
            "Книга", "Фильм", "Сериал", "Музыка", "Игра",
            "Спортинвентарь", "Журнал", "Радио", "Велосипед", "Сумка",
            "Компьютер", "Часы", "Телефон", "Техника", "Косметика",
            "Посуда", "Инструменты", "Детские игрушки,", "Обувь", "Аксессуары",
        };
    }

    private string? RndUniqueNames(string[]? strings, List<int> indexes)
    {
        var index = _rnd.Next(indexes.Count);
        var value = strings?[indexes[index]];
        indexes.RemoveAt(index);
        return value;
    }

    private ProductTypeModel GetRandomProductType()
    {
        var values = Enum.GetValues(typeof(ProductTypeModel));
        var rndTypeOfProduct = (ProductTypeModel)values.GetValue(_rnd.Next(values.Length))!;
        return rndTypeOfProduct;
    }

    [HttpGet("Index")]
    public IActionResult Index()
    {
        if (ProductModels.Count <= 0)
        {
            var products = GenerateProducts();
            return View("~/Views/Table/TableProducts.cshtml", products);
        }

        return View("~/Views/Table/TableProducts.cshtml", ProductModels);
    }

    [HttpGet("GenerateProducts")]
    public List<ProductModel?> GenerateProducts()
    {
        var namesIndexes = Enumerable.Range(0, Name!.Length).ToList();
        for (var i = 0; i <= 20; i++)
        {
            var id = Id++;
            var title = Title?[_rnd.Next(Title.Length)];
            var description = RndUniqueNames(Name, namesIndexes);
            var price = /*Math.Round(_rnd.NextDouble() * (10000 - 1) + 1, 2)*/ double.NaN;
            var count = _rnd.Next(0, 1000);
            var typeofProduct = GetRandomProductType();
            var product = new ProductModel(id, title, description, price, count, typeofProduct);
            ProductModels.Add(product);
        }

        return ProductModels;
    }

    [HttpPost("CreateProduct")]
    public IActionResult CreateProduct([FromBody] ProductModel? product)
    {
        if (product != null)
        {
            GenerateId(product);
            ProductModels.Add(product);
            return Ok(product);
        }

        return BadRequest();
    }

    [HttpPost("UpdateProduct/{id:int}")]
    public IActionResult UpdateProduct([FromBody] ProductModel updatedProduct, [FromRoute] int id)
    {
        var product = ProductModels.FirstOrDefault(p => p!.Id == id);
        if (product != null)
        {
            product.Title = updatedProduct.Title;
            product.Description = updatedProduct.Description;
            product.Price = updatedProduct.Price;
            product.Count = updatedProduct.Count;

            return Ok(product);
        }

        return NotFound();
    }

    [HttpDelete("DeleteProduct/{id:int}")]
    public IActionResult DeleteProduct([FromRoute] int id)
    {
        var product = ProductModels.FirstOrDefault(p => p!.Id == id);
        if (product != null)
        {
            ProductModels.Remove(product);
            return Ok();
        }

        return NotFound();
    }

    [HttpPost("GenerateID")]
    public void GenerateId(ProductModel? productModel)
    {
        productModel!.Id = Id++;
    }

    [HttpGet("GetProductById")]
    public ProductModel? GetProduct(int id)
    {
        return ProductModels.FirstOrDefault(i => i!.Id == id);
    }
}

HomeWorkEleven/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HomeWorkSix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/HomeWorkEleven.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeWorkEleven</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">TableProducts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Authorize">Authorize</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@if (IsSectionDefined("Footer"))
{
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;@await RenderSectionAsync("Footer", true) - 2023 – HomeWorkSix - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
}
else
{
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;Другой копирайтинг 2023 - HomeWorkSix - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
}


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>